// api/witz.js
export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET');
  
  const witze = [
  "Warum können Geister so schlecht lügen? Weil man durch sie hindurchsieht!",
  "Was macht ein Pirat am Computer? Er drückt die Enter-Taste!",
  "Warum ging der Pilz auf die Party? Weil er ein Champignon war!",
  "Was ist grün und steht vor der Tür? Ein Klopfsalat!",
  "Warum nehmen Skelette nie ein Bad? Weil sie bis auf die Knochen durchnässt werden!",
  "Was sagt ein Gen, wenn es ein anderes Gen trifft? Halogen!",
  "Warum können Bienen so gut rechnen? Weil sie den ganzen Tag mit Summen arbeiten!",
  "Was macht ein Clown im Büro? Faxen!",
  "Warum tragen Hühner keine Hosen? Weil das Ei sonst in die Hose geht!",
  "Was ist braun und schwimmt im Wasser? Ein U-Brot!",
  "Was macht ein Keks unter einem Baum? Krümel!",
  "Wie nennt man ein Reh mit Kontaktlinsen? Sehreh!",
  "Warum können Geheimagenten nie Fahrrad fahren? Weil sie immer im Geheimen unterwegs sind!",
  "Warum hat der Mathematiklehrer eine Brille? Damit er den Durchblick behält!",
  "Was ist orange und läuft durch den Wald? Eine Wanderine!",
  "Wie nennt man einen Bumerang, der nicht zurückkommt? Ein Stock!",
  "Warum können Skelette nicht lügen? Sie haben kein Rückgrat!",
  "Wie nennt man eine Gruppe von Wolfen, die Karten spielt? Pokerface!",
  "Was macht ein Pirat im Fitnessstudio? Er trainiert seine Plünderarme!",
  "Warum steht ein Pilz im Wald und lacht? Weil der Baum einen Witz gerissen hat!",
  "Warum ging der Gürtel ins Gefängnis? Weil er eine Hose hochgenommen hat!",
  "Was ist rot und schlecht für die Zähne? Ein Backstein!",
  "Warum können Elefanten nicht tanzen? Weil sie immer aus dem Takt trampeln!",
  "Wie nennt man einen Bären, der nach Regen riecht? Duschbär!",
  "Was macht ein Mathematiker beim Friseur? Er lässt sich die Wurzeln färben!",
  "Warum trinken Kühe keine Milch? Weil sie laktoseintolerant sind!",
  "Was macht ein Cowboy im Ruhestand? Er gibt den Lasso los!",
  "Warum sind Katzen schlechte DJs? Sie kratzen nur an den Platten!",
  "Wie nennt man einen Hund, der zaubern kann? Labrakadabrador!",
  "Was macht ein Schokokeks im Fitnessstudio? Er pumpt Schokolade!",
  "Warum können Seesterne nicht singen? Weil sie keine See-Stimme haben!",
  "Wie nennt man ein Krokodil mit GPS? Navi-Gator!",
  "Warum war der Computer kalt? Weil Windows offen war!",
  "Wie nennt man eine Ziege, die Witze erzählt? Meckerpott!",
  "Warum haben Fische keine Freunde? Weil sie immer so schuppig sind!",
  "Was sagt ein Ozean zum anderen? Nichts – sie winken nur!",
  "Wie nennt man eine Wolke, die Musik macht? Eine Wetter-Band!",
  "Warum war der Besen traurig? Weil er immer gefegt wurde!",
  "Wie nennt man ein Pferd auf dem Flur? Flur-reiter!",
  "Warum können Geometrielehrer keine Verbrecher fangen? Weil sie immer nur Winkel kennen!",
  "Wie nennt man eine Katze, die Maler ist? Leonardo da Miau!",
  "Was macht ein Elektriker im Garten? Er zieht Leitungen!",
  "Wie nennt man eine Gruppe singender Fische? Ein Orka-chor!",
  "Warum hat der Apfel einen Wurm? Weil er keinen Hund hat!",
  "Wie nennt man eine Kuh, die Musik macht? Moozart!",
  "Was ist weiß und rennt den Berg hoch? Eine Lawine auf dem Rückzug!",
  "Warum hat der Luftballon schlechte Laune? Er war total aufgeblasen!",
  "Wie nennt man eine faule Orange? Schlaorange!",
  "Warum können Gespenster so schlecht Tennis spielen? Weil sie immer durch den Schläger gehen!",
  "Was ist gelb und steht im Wald? Eine Banane mit Orientierungssinn!",
  "Wie nennt man ein Huhn, das in die Schule geht? Ein Bildungshuhn!",
  "Warum hat der Ozean keine Freunde? Weil er zu tief ist!",
  "Wie nennt man einen Delfin mit Brille? Seh-fin!",
  "Was macht ein Bauer im Fitnessstudio? Er trainiert seine Feldmuskeln!",
  "Warum sind Computer wie Mütter? Sie erinnern dich an alles, was du vergessen hast!",
  "Wie nennt man einen schlafenden Dinosaurier? Schnarchsaurus Rex!",
  "Warum können Geister so schlecht Fußball spielen? Weil sie immer durch die Abwehr gehen!",
  "Was sagt eine Null zur Acht? Schöner Gürtel!",
  "Warum ist der Pilz der Star im Wald? Weil er immer im Rampenlicht steht!",
  "Wie nennt man einen Bären, der keine Zähne hat? Gummibär!",
  "Warum sind Elefanten grau? Damit man sie nicht mit Kühlschränken verwechselt!",
  "Wie nennt man eine Gruppe von klugen Insekten? Denk-Käfer!",
  "Was ist der Lieblingstanz der Pinguine? Der Eis-Step!",
  "Warum essen Piraten keine Äpfel? Weil sie Angst vor Vitamin See haben!",
  "Wie nennt man ein Krokodil im Anzug? Investi-Gator!",
  "Was macht eine Uhr im Fitnessstudio? Sie trainiert ihre Sekunden!",
  "Warum haben Bäcker immer gute Laune? Weil sie ständig kneten dürfen!",
  "Wie nennt man eine Ente, die Witze erzählt? Lachente!",
  "Warum können Fische keine Mathe? Weil sie Angst vor dem Netz haben!",
  "Wie nennt man eine Kuh ohne Beine? Milchshake!",
  "Was sagt ein Toaster zum Brot? Ich bin heiß auf dich!",
  "Wie nennt man einen Delfin, der Trompete spielt? Flipper Louis!",
  "Warum haben Bäume so viele Freunde? Weil sie immer verwurzelt bleiben!",
  "Was macht ein Vampir auf dem Spielplatz? Er schaukelt im Blutmondlicht!",
  "Warum tragen Gärtner keine Anzüge? Weil sie lieber in die Erde gehen!",
  "Wie nennt man einen Hund, der Witze klaut? Plagiatador!",
  "Was macht ein Frosch im Internet? Er surft auf der Welle!",
  "Warum können Sterne nicht schlafen? Weil sie die ganze Nacht funkeln müssen!",
  "Wie nennt man einen faulen Astronauten? Raumfahrer auf Sparflamme!",
  "Warum hat der Bleistift gute Noten? Weil er immer mitgedacht hat!",
  "Wie nennt man eine Schildkröte ohne Panzer? Nacktschnecke auf Zeitreise!",
  "Was ist klein, grün und dreieckig? Ein Dreieckserbschen!",
  "Warum können Kühe keine Witze erzählen? Weil sie immer muhen müssen!",
  "Wie nennt man einen Bären, der Computer repariert? Tech-Bär!",
  "Was macht eine Schnecke auf dem Motorrad? Sie zieht Schleimspuren!",
  "Warum ist der Donut traurig? Weil er immer ein Loch im Herzen hat!",
  "Kommt ein Cowboy aus dem Friseur, Pony weg."
];

  
  const zufall = witze[Math.floor(Math.random() * witze.length)];

  const berlinZeit = new Date().toLocaleString('de-DE', {
    timeZone: 'Europe/Berlin',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  }).replace(',', '');

  res.status(200).json({
    witz: zufall,
    timestamp: berlinZeit
  });
}
